export const Images = {
  icLeave: require('./icons/ic_leave.png'),
  icClub2: require('./icons/ic_clubs2.png'),
  icClubA: require('./icons/ic_clubsA.png'),
  icDiamond2: require('./icons/ic_diamonds2.png'),
  icDiamond5: require('./icons/ic_diamonds5.png'),
  icDiamondA: require('./icons/ic_diamondsA.png'),
  icDiamondQ: require('./icons/ic_diamondsQ.png'),
  icCloseDeck: require('./icons/ic_closeDeck.png'),
  icClubKing: require('./icons/ic_clubsKing.png'),
  icClub7: require('./icons/ic_clubs7.png'),
  icHeart9: require('./icons/ic_hearts9.png'),
  icHeart6: require('./icons/ic_hearts6.png'),
  icHeartJ: require('./icons/ic_heartsJ.png'),
  icSpadesQueen: require('./icons/ic_spadesQueen.png'),
  icSpades2: require('./icons/ic_spades2.png'),
  icJoker: require('./icons/ic_Joker.png'),
  icBg: require('./icons/ic_bg.png'),
  icUser: require('./icons/ic_user.png'),
};
